### ISSUE TITLE
table of contents

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr-tutorial#147]
Where is the table of contents in the new tutorial? That was quite practical, you could skip quickly go to a part by just clicking on the chapter you are interested. 

Moreover I think that informations like 

> Source: vignettes/tutorial/devel/feature_selection.Rmd

at the beginning or 

> 
> Developed by Bernd Bischl, Michel Lang, Lars Kotthoff, Julia Schiffner, Jakob Richter, Zachary Jones, Giuseppe Casalicchio, Mason Gallo.
> 
> Site built with pkgdown.

at the end are quite unnecessary, and do not have to appear on every page.

**Comment by berndbischl** [comment]
> at the end are quite unnecessary, and do not have to appear on every page.

this can be removed, we should have one general page that lists authors.

**Comment by pat-s** [comment]
> Where is the table of contents in the new tutorial?

This is a know issue, see https://github.com/mlr-org/mlr/issues/2236

Also we deprecated this repo, please open all future issues concerning the tutorial at the main repo using the `tutorial` label

**Comment by pat-s** [comment]
To clarify a bit more: `pkgdown` currently only recognized headers up to a depth of 2. Due to formatting reasons of the pdf we need to start at h2 down to h4. These headers are not recognized atm.
Only using a patched `pkgdown` version for this is not worth it. However, I still have to open an issue for that in the `pkgdown` repo.

**Comment by pat-s** [comment]
Closing here as the issue with the ToC is listed in https://github.com/mlr-org/mlr/issues/2236
