### ISSUE TITLE
Add a chapter on clustering to the mlr tutorial

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr-tutorial#71]
As mentioned [here](https://github.com/mlr-org/mlr/issues/1414) we might need a dedicated chapter for clustering.

**Comment by schiffner** [comment]
Thx @jakob-r for transferring the issue.

The current tutorial structure is in the spirit of mlr in that it emphasizes the unified interface (make a task, make a learner, train it, etc.) instead of individual learning tasks.
So, it's good for folks that want to learn mlr in depth, but I agree, when you are in a hurry and/or just interested in how to solve a certain learning task it's tedious to collect the info scattered over multiple pages.

I wouldn't add a whole clustering chapter because it would just repeat the information that is already there in a different order (please correct me if something essential about clustering is missing).
Instead, I would add a "quick start" example for clustering.
Some background info: We have talked several times about extending the "quick start" section [here](http://mlr-org.github.io/mlr-tutorial/devel/html/). We plan to add short examples for all standard use cases. These should be complete (so that folks could copy and edit the code for their application), but without in-depth explanations -- just some hints where to find more information.

@rwarnung, @PhilippPro: Agreed?

**Comment by jakob-r** [comment]
I agree. After all it's about machine learning methods and they are interchangeable for the most part. There is no classification chapter - why should there be a clustering chapter.
Could you (@rwarnung) point which are special clustering features of mlr other than `makeClusterTask`?

**Comment by rwarnung** [comment]
@schiffner a quick start example sounds very good for me. Of course with enough abstraction it is not that different from other learners. I just didn't find it 100% clear how to do a cluster analysis using mlr.

@jakob-r you are right with enough efforts one (and I ;) ) is able to do it. I just thought addressing some things directly were good. E.g. I am often asked about the differences between caret and mlr and there are a lot (you know better than I do). For instance, as far as I know built-in stacking is a clear distinction. And if I think again clustering is one too. Thus making them easily available could draw further attention to the package.

**Comment by pat-s** [comment]
Following up on this, is there still a need for a clustering intro? If yes, who would be a person that has expertise in this? @rwarnung?

**Comment by jakob-r** [comment]
It might be part of the mlr hackathon at WhyR so let's close it here.

**Comment by rwarnung** [comment]
@pat-s thank you for coming back to my post. In fact I have played a bit but finally did not do that much clustering. So, unfortunately I don't really have that much expertise ... Thank you all for the work on mlr - I love it ! @jakob-r thank you too!

**Comment by pat-s** [comment]
> It might be part of the mlr hackathon at WhyR so let's close it here.

Ok!
